management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lms}
    username: ${SPRING_DATASOURCE_USERNAME:lms_user}
    password: ${SPRING_DATASOURCE_PASSWORD:lms_pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC